export const database = [
    {
       "name": "Luis Schiller",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1115.jpg",
       "hero_project": "pixel",
       "notes": "Architect orange",
       "email": "Margarett.Bergstrom46@gmail.com",
       "phone": "433-919-8878 x93604",
       "rating": "8",
       "status": false,
       "id": "1"
    },
    {
       "name": "Lois Schuppe",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1237.jpg",
       "hero_project": "feed",
       "notes": "wholly Bronze",
       "email": "Herman.Kautzer90@gmail.com",
       "phone": "492.839.7782 x477",
       "rating": "9",
       "status": false,
       "id": "2"
    },
    {
       "name": "Tamara Farrell",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/141.jpg",
       "hero_project": "array",
       "notes": "indexing Customer Program",
       "email": "Phoebe92@gmail.com",
       "phone": "(951) 250-4878 x19972",
       "rating": "7",
       "status": false,
       "id": "3"
    },
    {
       "name": "Dominick Okuneva",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/601.jpg",
       "hero_project": "alarm",
       "notes": "Chief Northwest",
       "email": "Lourdes.Dach54@gmail.com",
       "phone": "1-867-944-7692 x9895",
       "rating": "7",
       "status": false,
       "id": "4"
    },
    {
       "name": "Emilio Kulas",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/15.jpg",
       "hero_project": "feed",
       "notes": "easily wildly",
       "email": "Claudine_Daugherty@hotmail.com",
       "phone": "1-902-901-9250",
       "rating": "2",
       "status": false,
       "id": "5"
    },
    {
       "name": "Everett Veum",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/975.jpg",
       "hero_project": "port",
       "notes": "bypassing Jazz",
       "email": "Mattie.Shanahan19@hotmail.com",
       "phone": "439.326.6090 x9815",
       "rating": "5",
       "status": false,
       "id": "6"
    },
    {
       "name": "Steve Hoppe",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/868.jpg",
       "hero_project": "bus",
       "notes": "Cotton leverage Future",
       "email": "Boyd_Daniel88@yahoo.com",
       "phone": "1-431-737-4205 x6055",
       "rating": "6",
       "status": false,
       "id": "7"
    },
    {
       "name": "Samuel Nienow",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
       "hero_project": "microchip",
       "notes": "Rustic",
       "email": "Lizeth.Ryan1@yahoo.com",
       "phone": "1-280-718-9072",
       "rating": "3",
       "status": false,
       "id": "8"
    },
    {
       "name": "Mona Halvorson",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/717.jpg",
       "hero_project": "card",
       "notes": "siemens Nebraska Compatible",
       "email": "Jon_Waelchi@gmail.com",
       "phone": "979.325.3054 x37716",
       "rating": "6",
       "status": false,
       "id": "9"
    },
    {
       "name": "Max Jacobs",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/372.jpg",
       "hero_project": "transmitter",
       "notes": "virtual siemens yellow",
       "email": "Ayden56@yahoo.com",
       "phone": "636-325-0090 x8487",
       "rating": "6",
       "status": false,
       "id": "10"
    },
    {
       "name": "Belinda Kerluke",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/670.jpg",
       "hero_project": "bus",
       "notes": "Southeast Cambridgeshire Harrisonburg",
       "email": "Garett_Hills@gmail.com",
       "phone": "(916) 500-9827 x443",
       "rating": "2",
       "status": false,
       "id": "11"
    },
    {
       "name": "Herbert Runolfsdottir",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
       "hero_project": "capacitor",
       "notes": "Oklahoma",
       "email": "Crawford17@gmail.com",
       "phone": "1-820-916-6185 x0261",
       "rating": "7",
       "status": false,
       "id": "12"
    },
    {
       "name": "Priscilla Powlowski",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/763.jpg",
       "hero_project": "monitor",
       "notes": "Northeast Direct cyan",
       "email": "Lucio_Quigley@yahoo.com",
       "phone": "227.820.3807",
       "rating": "6",
       "status": false,
       "id": "13"
    },
    {
       "name": "Wilbur Hoppe",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/884.jpg",
       "hero_project": "circuit",
       "notes": "Jazz Rubber",
       "email": "Emerson_Nienow93@yahoo.com",
       "phone": "977-464-9673",
       "rating": "4",
       "status": false,
       "id": "14"
    },
    {
       "name": "Neal Kuhlman",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/857.jpg",
       "hero_project": "transmitter",
       "notes": "Sausages COM payment",
       "email": "Garnett_OConnell38@hotmail.com",
       "phone": "1-621-907-7432 x774",
       "rating": "7",
       "status": false,
       "id": "15"
    },
    {
       "name": "Lorraine Schroeder I",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1203.jpg",
       "hero_project": "pixel",
       "notes": "primary recrudesce optimize",
       "email": "Zella.Langosh@gmail.com",
       "phone": "397.984.9274 x70812",
       "rating": "6",
       "status": false,
       "id": "16"
    },
    {
       "name": "Jan Leffler",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/979.jpg",
       "hero_project": "array",
       "notes": "Gourde female",
       "email": "Zoey_Zieme69@hotmail.com",
       "phone": "1-497-222-3231",
       "rating": "4",
       "status": false,
       "id": "17"
    },
    {
       "name": "Tyrone Lemke",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/230.jpg",
       "hero_project": "hard drive",
       "notes": "Dickens trailer",
       "email": "Tierra.Prosacco@gmail.com",
       "phone": "(658) 698-5145",
       "rating": "8",
       "status": false,
       "id": "18"
    },
    {
       "name": "Natalie Durgan",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/984.jpg",
       "hero_project": "system",
       "notes": "District Lamborghini",
       "email": "Marc81@hotmail.com",
       "phone": "333-365-6276 x06174",
       "rating": "4",
       "status": false,
       "id": "19"
    },
    {
       "name": "Willie Jast",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/104.jpg",
       "hero_project": "capacitor",
       "notes": "on Solutions",
       "email": "Jovanny.Walter88@gmail.com",
       "phone": "582-366-8255 x2060",
       "rating": "9",
       "status": false,
       "id": "20"
    },
    {
       "name": "Della Gleichner",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/713.jpg",
       "hero_project": "system",
       "notes": "Cambridgeshire Applications Hungary",
       "email": "Aurore61@hotmail.com",
       "phone": "707.255.5969 x67537",
       "rating": "7",
       "status": false,
       "id": "21"
    },
    {
       "name": "Vernon Gorczany",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/164.jpg",
       "hero_project": "hard drive",
       "notes": "generate",
       "email": "Callie.Willms@gmail.com",
       "phone": "793-439-4614 x5076",
       "rating": "1",
       "status": false,
       "id": "22"
    },
    {
       "name": "Bruce Champlin Sr.",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/868.jpg",
       "hero_project": "application",
       "notes": "Lead National HTTP",
       "email": "Raoul_Hills@hotmail.com",
       "phone": "(384) 731-4717",
       "rating": "7",
       "status": false,
       "id": "23"
    },
    {
       "name": "Mr. Jaime Brakus",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/570.jpg",
       "hero_project": "port",
       "notes": "Mini seize beneath",
       "email": "Camilla.Fadel2@yahoo.com",
       "phone": "1-217-930-6078 x281",
       "rating": "7",
       "status": false,
       "id": "24"
    },
    {
       "name": "Nancy Muller",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/221.jpg",
       "hero_project": "interface",
       "notes": "South",
       "email": "Casandra_Wolff@gmail.com",
       "phone": "436.625.5633",
       "rating": "6",
       "status": false,
       "id": "25"
    },
    {
       "name": "Elizabeth Cruickshank",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/394.jpg",
       "hero_project": "interface",
       "notes": "lumen Korean",
       "email": "Theron68@hotmail.com",
       "phone": "1-530-261-6954 x71026",
       "rating": "9",
       "status": false,
       "id": "26"
    },
    {
       "name": "Dominic Gusikowski",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/578.jpg",
       "hero_project": "hard drive",
       "notes": "Director",
       "email": "Godfrey_Pacocha76@gmail.com",
       "phone": "241.459.7103 x2992",
       "rating": "3",
       "status": false,
       "id": "27"
    },
    {
       "name": "Adrienne Dooley",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/369.jpg",
       "hero_project": "application",
       "notes": "within Bronze South",
       "email": "Therese_Collins49@hotmail.com",
       "phone": "607-710-1196 x29368",
       "rating": "7",
       "status": false,
       "id": "28"
    },
    {
       "name": "Douglas Mraz MD",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/195.jpg",
       "hero_project": "pixel",
       "notes": "Grocery mediocre Ridge",
       "email": "Kennith_Jerde32@yahoo.com",
       "phone": "657.263.4051 x1048",
       "rating": "7",
       "status": false,
       "id": "29"
    },
    {
       "name": "Jon Steuber",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1224.jpg",
       "hero_project": "card",
       "notes": "quisquam Generic teal",
       "email": "April.Hills42@gmail.com",
       "phone": "992-420-5367 x576",
       "rating": "5",
       "status": false,
       "id": "30"
    },
    {
       "name": "Richard Bradtke",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1036.jpg",
       "hero_project": "feed",
       "notes": "Krona united Mobile",
       "email": "Kiera.Witting@hotmail.com",
       "phone": "471.796.9396 x060",
       "rating": "6",
       "status": false,
       "id": "31"
    },
    {
       "name": "Norma Hettinger II",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/278.jpg",
       "hero_project": "port",
       "notes": "grey",
       "email": "Samara_Brakus@yahoo.com",
       "phone": "864.913.3752 x523",
       "rating": "7",
       "status": false,
       "id": "32"
    },
    {
       "name": "Raquel Kunze",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/569.jpg",
       "hero_project": "card",
       "notes": "Clothing",
       "email": "Loyce_McKenzie@hotmail.com",
       "phone": "846.676.7706",
       "rating": "1",
       "status": false,
       "id": "33"
    },
    {
       "name": "Casey Lind",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/785.jpg",
       "hero_project": "program",
       "notes": "Male redundant",
       "email": "Myah82@hotmail.com",
       "phone": "1-688-530-1909 x183",
       "rating": "8",
       "status": false,
       "id": "34"
    },
    {
       "name": "Hattie Brakus",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1107.jpg",
       "hero_project": "protocol",
       "notes": "pace",
       "email": "Aron.Mitchell@gmail.com",
       "phone": "(976) 294-7184 x54579",
       "rating": "4",
       "status": false,
       "id": "35"
    },
    {
       "name": "Ronnie Nienow Sr.",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/360.jpg",
       "hero_project": "driver",
       "notes": "SSL Wooden Games",
       "email": "Orland.Kulas@yahoo.com",
       "phone": "(783) 919-1304",
       "rating": "3",
       "status": false,
       "id": "36"
    },
    {
       "name": "Mr. Patrick Skiles",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/842.jpg",
       "hero_project": "bus",
       "notes": "Buckinghamshire Rock",
       "email": "Dangelo66@hotmail.com",
       "phone": "1-235-441-6863",
       "rating": "9",
       "status": false,
       "id": "37"
    },
    {
       "name": "Terri Robel",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/785.jpg",
       "hero_project": "hard drive",
       "notes": "phew",
       "email": "Coy_Altenwerth98@gmail.com",
       "phone": "616-248-0893 x436",
       "rating": "3",
       "status": false,
       "id": "38"
    },
    {
       "name": "Tammy Spinka",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/419.jpg",
       "hero_project": "hard drive",
       "notes": "within Horizontal",
       "email": "Tillman68@gmail.com",
       "phone": "1-450-420-3080",
       "rating": "9",
       "status": false,
       "id": "39"
    },
    {
       "name": "Sadie Hermiston",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/35.jpg",
       "hero_project": "microchip",
       "notes": "Avon",
       "email": "Isac_Murray73@yahoo.com",
       "phone": "1-906-246-3297 x3425",
       "rating": "5",
       "status": false,
       "id": "40"
    },
    {
       "name": "Ashley Blanda",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1189.jpg",
       "hero_project": "feed",
       "notes": "Ames generate Ohio",
       "email": "Layla_Zieme@hotmail.com",
       "phone": "(220) 238-4982 x88668",
       "rating": "2",
       "status": false,
       "id": "41"
    },
    {
       "name": "Wilson Kutch",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/671.jpg",
       "hero_project": "microchip",
       "notes": "green tenderly",
       "email": "Abbigail47@gmail.com",
       "phone": "797-652-2402",
       "rating": "8",
       "status": false,
       "id": "42"
    },
    {
       "name": "Ramiro Wiegand",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/926.jpg",
       "hero_project": "firewall",
       "notes": "numquam Books",
       "email": "Cristopher.Lueilwitz@hotmail.com",
       "phone": "892-705-7145 x18632",
       "rating": "6",
       "status": false,
       "id": "43"
    },
    {
       "name": "Vickie Metz",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1174.jpg",
       "hero_project": "circuit",
       "notes": "Designer Generic questionably",
       "email": "Akeem.Buckridge@yahoo.com",
       "phone": "345.640.6946 x23708",
       "rating": "1",
       "status": false,
       "id": "44"
    },
    {
       "name": "Mrs. Angelo Upton",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/637.jpg",
       "hero_project": "application",
       "notes": "transmitter Electronic except",
       "email": "Jaron_Turner@yahoo.com",
       "phone": "1-922-704-2930 x39625",
       "rating": "1",
       "status": false,
       "id": "45"
    },
    {
       "name": "Greg Hudson",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/924.jpg",
       "hero_project": "feed",
       "notes": "Infrastructure",
       "email": "Keven_Cronin@hotmail.com",
       "phone": "351-811-0586 x80258",
       "rating": "6",
       "status": false,
       "id": "46"
    },
    {
       "name": "Phillip Feil",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1164.jpg",
       "hero_project": "transmitter",
       "notes": "innovate",
       "email": "Alisa_Zboncak93@gmail.com",
       "phone": "1-332-933-7006 x512",
       "rating": "6",
       "status": false,
       "id": "47"
    },
    {
       "name": "Nichole Franey",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1012.jpg",
       "hero_project": "program",
       "notes": "circa",
       "email": "Ally_Fisher50@gmail.com",
       "phone": "(598) 905-3224 x11239",
       "rating": "5",
       "status": false,
       "id": "48"
    },
    {
       "name": "Geoffrey Barton II",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1240.jpg",
       "hero_project": "panel",
       "notes": "Southwest hacking",
       "email": "Peyton70@yahoo.com",
       "phone": "1-588-459-7405",
       "rating": "8",
       "status": false,
       "id": "49"
    },
    {
       "name": "Miss Randal Pfannerstill",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/654.jpg",
       "hero_project": "feed",
       "notes": "Zirconium",
       "email": "Enoch70@hotmail.com",
       "phone": "454-809-1612 x65512",
       "rating": "1",
       "status": false,
       "id": "50"
    },
    {
       "name": "Sarah Stark",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1157.jpg",
       "hero_project": "sensor",
       "notes": "Missouri Rupiah",
       "email": "Ahmed.Schultz21@gmail.com",
       "phone": "243-357-4542",
       "rating": "6",
       "status": false,
       "id": "51"
    },
    {
       "name": "Ms. Desiree Lehner",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/26.jpg",
       "hero_project": "hard drive",
       "notes": "modular",
       "email": "Alfonzo78@gmail.com",
       "phone": "1-650-444-1879 x317",
       "rating": "7",
       "status": false,
       "id": "52"
    },
    {
       "name": "Dr. Andrew Collins",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/29.jpg",
       "hero_project": "firewall",
       "notes": "Afghani navigate",
       "email": "Elsa56@hotmail.com",
       "phone": "644.392.6577",
       "rating": "4",
       "status": false,
       "id": "53"
    },
    {
       "name": "Louis Pollich",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/340.jpg",
       "hero_project": "program",
       "notes": "Northwest",
       "email": "Sid24@gmail.com",
       "phone": "822-338-9423 x8167",
       "rating": "2",
       "status": false,
       "id": "54"
    },
    {
       "name": "Ross Luettgen",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/44.jpg",
       "hero_project": "transmitter",
       "notes": "Diesel Convertible Health",
       "email": "Beulah.Kassulke46@hotmail.com",
       "phone": "752-253-6668 x842",
       "rating": "7",
       "status": false,
       "id": "55"
    },
    {
       "name": "Belinda Goodwin",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/554.jpg",
       "hero_project": "monitor",
       "notes": "Hampshire est",
       "email": "Antonina_Boehm27@hotmail.com",
       "phone": "471-340-9045",
       "rating": "4",
       "status": false,
       "id": "56"
    },
    {
       "name": "Leland Runolfsdottir",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/562.jpg",
       "hero_project": "bandwidth",
       "notes": "ADP Identity Jewelery",
       "email": "Ethel.Abernathy66@yahoo.com",
       "phone": "1-500-258-2189 x427",
       "rating": "1",
       "status": false,
       "id": "57"
    },
    {
       "name": "Sara Gutkowski",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/332.jpg",
       "hero_project": "array",
       "notes": "Specialist Overpass",
       "email": "Eveline.Larkin81@hotmail.com",
       "phone": "766.649.2130 x96809",
       "rating": "2",
       "status": false,
       "id": "58"
    },
    {
       "name": "Ellis Runolfsson I",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/157.jpg",
       "hero_project": "card",
       "notes": "Practical",
       "email": "Gayle_Ratke@yahoo.com",
       "phone": "1-211-246-4294 x127",
       "rating": "8",
       "status": false,
       "id": "59"
    },
    {
       "name": "Dwayne Bergnaum",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/209.jpg",
       "hero_project": "array",
       "notes": "minus",
       "email": "Kendra_Zieme@yahoo.com",
       "phone": "1-902-434-1591 x07566",
       "rating": "3",
       "status": false,
       "id": "60"
    },
    {
       "name": "Iris Kozey",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/23.jpg",
       "hero_project": "matrix",
       "notes": "indeed Ball",
       "email": "Verna_Kshlerin0@hotmail.com",
       "phone": "382-751-0730 x314",
       "rating": "9",
       "status": false,
       "id": "61"
    },
    {
       "name": "Irvin Cassin",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/265.jpg",
       "hero_project": "panel",
       "notes": "technologies Cambridgeshire Germanium",
       "email": "Kaylin53@gmail.com",
       "phone": "245.514.3799 x840",
       "rating": "9",
       "status": false,
       "id": "62"
    },
    {
       "name": "Johnny Greenfelder",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1074.jpg",
       "hero_project": "microchip",
       "notes": "teal less sans",
       "email": "Ahmad_Mertz79@hotmail.com",
       "phone": "1-975-363-3631 x3910",
       "rating": "5",
       "status": false,
       "id": "63"
    },
    {
       "name": "Rodolfo Bogan",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/203.jpg",
       "hero_project": "capacitor",
       "notes": "Analyst",
       "email": "Bradley.OHara@yahoo.com",
       "phone": "243.975.4702 x0716",
       "rating": "6",
       "status": false,
       "id": "64"
    },
    {
       "name": "Mamie Kuvalis PhD",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/187.jpg",
       "hero_project": "firewall",
       "notes": "eyeballs Northeast synthesize",
       "email": "Mossie61@gmail.com",
       "phone": "856.654.8838 x7503",
       "rating": "9",
       "status": false,
       "id": "65"
    },
    {
       "name": "Randall Farrell",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1078.jpg",
       "hero_project": "panel",
       "notes": "Assimilated magenta firmware",
       "email": "Kariane.Rippin@yahoo.com",
       "phone": "873-888-6180 x327",
       "rating": "2",
       "status": false,
       "id": "66"
    },
    {
       "name": "Naomi Gottlieb",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1163.jpg",
       "hero_project": "feed",
       "notes": "Music",
       "email": "Murphy77@hotmail.com",
       "phone": "1-853-484-9143 x905",
       "rating": "2",
       "status": false,
       "id": "67"
    },
    {
       "name": "Lorenzo Leannon",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1037.jpg",
       "hero_project": "capacitor",
       "notes": "educated South",
       "email": "Marianna6@yahoo.com",
       "phone": "656-461-8970 x908",
       "rating": "6",
       "status": false,
       "id": "68"
    },
    {
       "name": "Randal Schuppe",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/262.jpg",
       "hero_project": "sensor",
       "notes": "virtual Sausages wireless",
       "email": "Laurel8@yahoo.com",
       "phone": "(797) 325-5285 x0216",
       "rating": "6",
       "status": false,
       "id": "69"
    },
    {
       "name": "Stephen Hoeger",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/374.jpg",
       "hero_project": "microchip",
       "notes": "Engineer Steel functionalities",
       "email": "Raheem.Schneider@hotmail.com",
       "phone": "912.737.9737 x4202",
       "rating": "3",
       "status": false,
       "id": "70"
    },
    {
       "name": "Phyllis Harber",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/403.jpg",
       "hero_project": "transmitter",
       "notes": "up",
       "email": "Theresia.Donnelly42@hotmail.com",
       "phone": "570-225-5781",
       "rating": "5",
       "status": false,
       "id": "71"
    },
    {
       "name": "Miranda O'Hara",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1210.jpg",
       "hero_project": "pixel",
       "notes": "Cheese female Northwest",
       "email": "Dorris_Rice84@hotmail.com",
       "phone": "(541) 637-1518 x05112",
       "rating": "2",
       "status": false,
       "id": "72"
    },
    {
       "name": "Miss Corey Flatley",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1195.jpg",
       "hero_project": "feed",
       "notes": "South",
       "email": "Ronaldo_Schaefer@yahoo.com",
       "phone": "535-416-3734",
       "rating": "6",
       "status": false,
       "id": "73"
    },
    {
       "name": "Reginald Reynolds",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1179.jpg",
       "hero_project": "circuit",
       "notes": "Licensed Profound",
       "email": "Rickey_Botsford@gmail.com",
       "phone": "400-481-5361 x439",
       "rating": "7",
       "status": false,
       "id": "74"
    },
    {
       "name": "Deborah Schultz",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/817.jpg",
       "hero_project": "monitor",
       "notes": "THX background",
       "email": "Brennan_Adams15@gmail.com",
       "phone": "401.823.3577 x4565",
       "rating": "6",
       "status": false,
       "id": "75"
    },
    {
       "name": "Dr. Clara Kuhlman",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/316.jpg",
       "hero_project": "sensor",
       "notes": "Research Hryvnia",
       "email": "Rashad72@gmail.com",
       "phone": "962-295-5609",
       "rating": "2",
       "status": false,
       "id": "76"
    },
    {
       "name": "Nicole Morissette",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1188.jpg",
       "hero_project": "transmitter",
       "notes": "Other Persistent parse",
       "email": "Jade.Jacobs@gmail.com",
       "phone": "622.636.0218",
       "rating": "6",
       "status": false,
       "id": "77"
    },
    {
       "name": "Mr. Jordan Hintz",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1111.jpg",
       "hero_project": "protocol",
       "notes": "Fremont Supervisor",
       "email": "Jessy.Ortiz@yahoo.com",
       "phone": "1-622-734-2444 x707",
       "rating": "5",
       "status": false,
       "id": "78"
    },
    {
       "name": "Leonard Lang",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/973.jpg",
       "hero_project": "panel",
       "notes": "Trans content Krona",
       "email": "Weldon85@gmail.com",
       "phone": "339-286-9217",
       "rating": "8",
       "status": false,
       "id": "79"
    },
    {
       "name": "Justin Funk",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/574.jpg",
       "hero_project": "array",
       "notes": "South Taiwan",
       "email": "Dandre47@yahoo.com",
       "phone": "203.634.9147 x5245",
       "rating": "6",
       "status": false,
       "id": "80"
    },
    {
       "name": "Dr. Nick Hackett",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1123.jpg",
       "hero_project": "card",
       "notes": "Hybrid EXE Diesel",
       "email": "Rickie_Barrows@hotmail.com",
       "phone": "605.593.5704 x4150",
       "rating": "4",
       "status": false,
       "id": "81"
    },
    {
       "name": "Leslie Marvin",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/773.jpg",
       "hero_project": "application",
       "notes": "intranet",
       "email": "Beulah19@gmail.com",
       "phone": "1-523-251-4467",
       "rating": "7",
       "status": false,
       "id": "82"
    },
    {
       "name": "Heidi Lindgren",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/223.jpg",
       "hero_project": "firewall",
       "notes": "drop Concrete",
       "email": "Creola.Kassulke@yahoo.com",
       "phone": "1-460-309-8430",
       "rating": "5",
       "status": false,
       "id": "83"
    },
    {
       "name": "Vera Upton III",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/79.jpg",
       "hero_project": "monitor",
       "notes": "tangible",
       "email": "Elian_Kemmer@yahoo.com",
       "phone": "790.349.9355 x72315",
       "rating": "6",
       "status": false,
       "id": "84"
    },
    {
       "name": "Mrs. Orville Legros",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/248.jpg",
       "hero_project": "sensor",
       "notes": "Metairie er",
       "email": "Nat_Kozey@gmail.com",
       "phone": "(297) 662-0319 x718",
       "rating": "6",
       "status": false,
       "id": "85"
    },
    {
       "name": "Dale Hammes",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/56.jpg",
       "hero_project": "driver",
       "notes": "District Small Metrics",
       "email": "Kali.Mitchell@hotmail.com",
       "phone": "870.858.4362 x8300",
       "rating": "8",
       "status": false,
       "id": "86"
    },
    {
       "name": "Levi King",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/835.jpg",
       "hero_project": "panel",
       "notes": "Gloves",
       "email": "Hadley.Bradtke96@yahoo.com",
       "phone": "1-644-738-2108 x986",
       "rating": "4",
       "status": false,
       "id": "87"
    },
    {
       "name": "Marlene King Sr.",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/939.jpg",
       "hero_project": "feed",
       "notes": "Reactive male applications",
       "email": "Aisha_Pfannerstill38@yahoo.com",
       "phone": "(275) 341-9824 x8203",
       "rating": "5",
       "status": false,
       "id": "88"
    },
    {
       "name": "Shaun Hackett",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/836.jpg",
       "hero_project": "interface",
       "notes": "reciprocal integrate reprehenderit",
       "email": "Chelsey_Schinner@yahoo.com",
       "phone": "588.879.7256 x984",
       "rating": "7",
       "status": false,
       "id": "89"
    },
    {
       "name": "Ms. Irene Thiel",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/108.jpg",
       "hero_project": "bandwidth",
       "notes": "warmly installation",
       "email": "Rosanna4@gmail.com",
       "phone": "523-814-6909",
       "rating": "7",
       "status": false,
       "id": "90"
    },
    {
       "name": "Tim Murray",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/314.jpg",
       "hero_project": "bandwidth",
       "notes": "Gold Fish Incredible",
       "email": "Kara_Stoltenberg@yahoo.com",
       "phone": "690.604.6896 x1415",
       "rating": "9",
       "status": false,
       "id": "91"
    },
    {
       "name": "Boyd Kunze",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/610.jpg",
       "hero_project": "pixel",
       "notes": "Pants Tantalum",
       "email": "Isaac_Lehner26@yahoo.com",
       "phone": "402.881.4572 x35159",
       "rating": "9",
       "status": false,
       "id": "92"
    },
    {
       "name": "Jeanne Kris",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/359.jpg",
       "hero_project": "transmitter",
       "notes": "Table",
       "email": "Esperanza.Kuhn@yahoo.com",
       "phone": "(254) 638-5886",
       "rating": "6",
       "status": false,
       "id": "93"
    },
    {
       "name": "Alma Marvin",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1095.jpg",
       "hero_project": "transmitter",
       "notes": "female mmm Kingdom",
       "email": "Jennyfer1@gmail.com",
       "phone": "987.378.3449",
       "rating": "8",
       "status": false,
       "id": "94"
    },
    {
       "name": "Claude Leuschke",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1188.jpg",
       "hero_project": "system",
       "notes": "Bicycle streamline",
       "email": "Willis.Kemmer34@hotmail.com",
       "phone": "(362) 784-4255 x889",
       "rating": "3",
       "status": false,
       "id": "95"
    },
    {
       "name": "Miss Jessie Oberbrunner Sr.",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/803.jpg",
       "hero_project": "hard drive",
       "notes": "Volkswagen sore very",
       "email": "Iva.Torp51@yahoo.com",
       "phone": "(204) 439-3590 x6124",
       "rating": "9",
       "status": false,
       "id": "96"
    },
    {
       "name": "Carole Nikolaus",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/63.jpg",
       "hero_project": "circuit",
       "notes": "Clarksville that",
       "email": "Mack_Anderson@gmail.com",
       "phone": "778.277.1956 x3570",
       "rating": "4",
       "status": false,
       "id": "97"
    },
    {
       "name": "Ken Grimes",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/396.jpg",
       "hero_project": "application",
       "notes": "Guinea Fantastic",
       "email": "Bethany51@gmail.com",
       "phone": "650.685.1878 x22570",
       "rating": "7",
       "status": false,
       "id": "98"
    },
    {
       "name": "Barbara Frami",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/688.jpg",
       "hero_project": "protocol",
       "notes": "woman XML",
       "email": "Camden_Stark@yahoo.com",
       "phone": "1-968-384-2410 x7600",
       "rating": "3",
       "status": false,
       "id": "99"
    },
    {
       "name": "Jody O'Reilly",
       "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/712.jpg",
       "hero_project": "system",
       "notes": "Jewelery Bike primary",
       "email": "Jazmin.OHara84@yahoo.com",
       "phone": "754.230.1176 x146",
       "rating": "3",
       "status": false,
       "id": "100"
    }
 ] 